# Generated by Django 3.0 on 2019-12-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
